services:
  db:
    env_file:
      - .env
    image: "postgres:17.3-alpine3.21"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_task_tracker:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_PASSWORD}" ]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    env_file:
      - .env
    build: .
    image: "task-tracker:latest"
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_task_tracker: